# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20170319_1823'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='channel',
            managers=[
            ],
        ),
    ]
